export default function buildHomeUserViewConfig({
  schoolState,
  schoolUi,
  docenteState,
  derived,
  handlers
}) {
  return {
    colegios: {
      ...schoolState,
      isEditingColegio: schoolUi.isEditingColegio,
      colegiosSuccess: schoolUi.colegiosSuccess,
      colegioSuccessAnim: schoolUi.colegioSuccessAnim,
      mobileColegioControlsRowStyle: derived.mobileColegioControlsRowStyle,
      mobileColegioControlBtnStyle: derived.mobileColegioControlBtnStyle,
      mobileColegioControlRowStyle: derived.mobileColegioControlRowStyle,
      mobileColegioControlTextStyle: derived.mobileColegioControlTextStyle,
      rectoresRegistrados: derived.rectoresRegistrados,
      rectoresFiltrados: derived.rectoresFiltrados,
      handleSaveColegio: handlers.colegios.handleSaveColegio,
      cancelColegioEdit: handlers.colegios.cancelColegioEdit,
      openRectorEditModal: handlers.colegios.openRectorEditModal,
      askDeleteRector: handlers.colegios.askDeleteRector,
      startEditColegio: handlers.colegios.startEditColegio,
      askDeleteColegio: handlers.colegios.askDeleteColegio,
      closeColegiosModal: handlers.colegios.closeColegiosModal,
      closeColegiosListModal: handlers.colegios.closeColegiosListModal
    },
    docentes: {
      NIVEL_OPTIONS: derived.NIVEL_OPTIONS,
      ...docenteState,
      resolveSedeNombreForView: derived.resolveSedeNombreForView,
      getNivelLabel: derived.getNivelLabel,
      getNivelShortLabel: derived.getNivelShortLabel,
      canAdminFilterDocenteSchools: derived.canAdminFilterDocenteSchools,
      colegiosLoading: schoolState.colegiosLoading,
      colegiosOptions: schoolState.colegiosOptions,
      sortCursosForDisplay: derived.sortCursosForDisplay,
      resolveColegioNombreForView: derived.resolveColegioNombreForView,
      handleResetDocentePassword: handlers.docentes.handleResetDocentePassword,
      openAdminDocenteEditModal: handlers.docentes.openAdminDocenteEditModal,
      askDeleteDocente: handlers.docentes.askDeleteDocente,
      sanitizeDocenteNombreInput: handlers.docentes.sanitizeDocenteNombreInput,
      normalizeDocenteEmailInput: handlers.docentes.normalizeDocenteEmailInput,
      resetDocenteFormState: handlers.docentes.resetDocenteFormState,
      openDocenteNivelConfigModal: handlers.docentes.openDocenteNivelConfigModal,
      openDocenteCursosConfigModal: handlers.docentes.openDocenteCursosConfigModal,
      handleSaveDocente: handlers.docentes.handleSaveDocente,
      closeAdminDocenteEditModal: handlers.docentes.closeAdminDocenteEditModal,
      parseMateriasTexto: handlers.docentes.parseMateriasTexto,
      closeDocenteCrudListModal: handlers.docentes.closeDocenteCrudListModal,
      docentesSearchNormalized: derived.docentesSearchNormalized,
      docentesSearchSuggestions: derived.docentesSearchSuggestions,
      docentesFiltrados: derived.docentesFiltrados,
      adminDocentesFiltrados: derived.adminDocentesFiltrados,
      colegioSeleccionadoNombre: derived.colegioSeleccionadoNombre,
      loadDocentesColegio: handlers.docentes.loadDocentesColegio,
      handleSelectDocenteCrudColegio: handlers.docentes.handleSelectDocenteCrudColegio,
      updateDocenteMateriaDraft: handlers.docentes.updateDocenteMateriaDraft,
      commitDocenteMateriaDraft: handlers.docentes.commitDocenteMateriaDraft,
      toggleDocenteCurso: handlers.docentes.toggleDocenteCurso,
      closeDocenteNivelConfigModal: handlers.docentes.closeDocenteNivelConfigModal,
      closeDocenteCursosConfigModal: handlers.docentes.closeDocenteCursosConfigModal,
      closeDocenteCrudModal: handlers.docentes.closeDocenteCrudModal,
      closeDocentesModal: handlers.docentes.closeDocentesModal
    }
  };
}
