export default function buildHomeAcademicViewConfig({
  app,
  schoolState,
  courseState,
  estudianteState,
  periodState,
  docenteState,
  derived,
  handlers
}) {
  return {
    docentePanel: {
      docentePanelModalVisible: docenteState.docentePanelModalVisible,
      setDocentePanelModalVisible: docenteState.setDocentePanelModalVisible,
      docentePerfilLoading: derived.docentePerfilLoading,
      docentePerfilError: derived.docentePerfilError,
      docentePerfilCursos: derived.docentePerfilCursos,
      docenteMateriasAsignadasTotal: derived.docenteMateriasAsignadasTotal,
      openCreateEstudianteModal: handlers.estudiantes.openCreateEstudianteModal
    },
    estudiantesCreate: {
      estudianteCreateModalVisible: estudianteState.estudianteCreateModalVisible,
      closeCreateEstudianteModal: handlers.estudiantes.closeCreateEstudianteModal,
      loadingCursos: courseState.loadingCursos,
      savingEstudiante: estudianteState.savingEstudiante,
      estudianteCreateCursoPickerOpen: estudianteState.estudianteCreateCursoPickerOpen,
      setEstudianteCreateCursoPickerOpen: estudianteState.setEstudianteCreateCursoPickerOpen,
      estudianteCreateCursoNombre: derived.estudianteCreateCursoNombre,
      cursosAsignados: derived.cursosAsignados,
      estudianteCreateCursoId: estudianteState.estudianteCreateCursoId,
      changeEstudianteCreateCurso: handlers.estudiantes.changeEstudianteCreateCurso,
      estudianteCreateMateriasDisponibles: derived.estudianteCreateMateriasDisponibles,
      estudianteCreateMaterias: estudianteState.estudianteCreateMaterias,
      normalizeMateriaOption: derived.normalizeMateriaOption,
      toggleEstudianteCreateMateria: handlers.estudiantes.toggleEstudianteCreateMateria,
      estudianteCreateForm: estudianteState.estudianteCreateForm,
      setEstudianteCreateForm: estudianteState.setEstudianteCreateForm,
      handleImportCsv: handlers.estudiantes.handleImportCsv,
      selectedCsvFile: estudianteState.selectedCsvFile,
      downloadExcelTemplate: handlers.estudiantes.downloadExcelTemplate,
      downloadingTemplate: estudianteState.downloadingTemplate,
      estudianteCreateError: estudianteState.estudianteCreateError,
      uploadedStudents: estudianteState.uploadedStudents,
      handleCreateEstudiante: handlers.estudiantes.handleCreateEstudiante
    },
    estudiantesList: {
      estudiantesModalVisible: estudianteState.estudiantesModalVisible,
      closeEstudiantesModal: handlers.estudiantes.closeEstudiantesModal,
      resolveColegioNombreForView: derived.resolveColegioNombreForView,
      estudiantesColegioId: estudianteState.estudiantesColegioId,
      setEstudiantesColegioPickerOpen: estudianteState.setEstudiantesColegioPickerOpen,
      estudiantesColegioPickerOpen: estudianteState.estudiantesColegioPickerOpen,
      colegiosLoading: schoolState.colegiosLoading,
      colegiosOptions: schoolState.colegiosOptions,
      changeEstudiantesColegio: handlers.estudiantes.changeEstudiantesColegio,
      cursoSeleccionadoNombre: derived.cursoSeleccionadoNombre,
      setCursoPickerOpen: estudianteState.setCursoPickerOpen,
      cursoPickerOpen: estudianteState.cursoPickerOpen,
      loadingCursos: courseState.loadingCursos,
      cursosAsignados: derived.cursosAsignados,
      cursoSeleccionado: estudianteState.cursoSeleccionado,
      selectCursoEstudiantes: handlers.estudiantes.selectCursoEstudiantes,
      estudiantesMateriasDisponibles: derived.estudiantesMateriasDisponibles,
      setEstudianteMateriaPickerOpen: estudianteState.setEstudianteMateriaPickerOpen,
      estudianteMateriaPickerOpen: estudianteState.estudianteMateriaPickerOpen,
      estudianteMateriaFiltro: estudianteState.estudianteMateriaFiltro,
      ALL_MATERIAS_OPTION: derived.ALL_MATERIAS_OPTION,
      setEstudianteMateriaFiltro: estudianteState.setEstudianteMateriaFiltro,
      normalizeMateriaOption: derived.normalizeMateriaOption,
      downloadingQrZip: estudianteState.downloadingQrZip,
      downloadEstudiantesQrZip: handlers.estudiantes.downloadEstudiantesQrZip,
      estudiantesLoading: estudianteState.estudiantesLoading,
      estudiantesError: estudianteState.estudiantesError,
      estudiantesFiltrados: derived.estudiantesFiltrados,
      qrZipProgress: estudianteState.qrZipProgress,
      estudianteEditing: estudianteState.estudianteEditing,
      estudianteEditForm: estudianteState.estudianteEditForm,
      setEstudianteEditForm: estudianteState.setEstudianteEditForm,
      savingEstudianteEdit: estudianteState.savingEstudianteEdit,
      toggleEstudianteEditMateria: handlers.estudiantes.toggleEstudianteEditMateria,
      handleUpdateEstudiante: handlers.estudiantes.handleUpdateEstudiante,
      cancelEditEstudiante: handlers.estudiantes.cancelEditEstudiante,
      startEditEstudiante: handlers.estudiantes.startEditEstudiante,
      askDeleteEstudiante: handlers.estudiantes.askDeleteEstudiante
    },
    periodos: {
      periodModalVisible: periodState.periodModalVisible,
      closePeriodModal: handlers.periodos.closePeriodModal,
      periodModalScrollRef: periodState.periodModalScrollRef,
      editingPeriodo: periodState.editingPeriodo,
      canAdminFilterPeriodSchools: derived.canAdminFilterPeriodSchools,
      periodSchoolId: periodState.periodSchoolId,
      periodSchoolPickerOpen: periodState.periodSchoolPickerOpen,
      setPeriodSchoolPickerOpen: periodState.setPeriodSchoolPickerOpen,
      setPeriodSchoolId: periodState.setPeriodSchoolId,
      setEditingPeriodo: periodState.setEditingPeriodo,
      periodForm: periodState.periodForm,
      setPeriodForm: periodState.setPeriodForm,
      periodos: periodState.periodos,
      periodFeedback: periodState.periodFeedback,
      setPeriodFeedback: periodState.setPeriodFeedback,
      days: derived.days,
      months: derived.months,
      years: derived.years,
      hours: derived.hours,
      minutes: derived.minutes,
      monthNames: derived.monthNames,
      adjustValue: handlers.periodos.adjustValue,
      cycleValue: handlers.periodos.cycleValue,
      savingPeriodo: periodState.savingPeriodo,
      handleSavePeriod: handlers.periodos.handleSavePeriod,
      formatPeriodSummary: derived.formatPeriodSummary,
      formatPeriodDate: derived.formatPeriodDate,
      formatPeriodTime: derived.formatPeriodTime,
      getPeriodDurationLabel: derived.getPeriodDurationLabel,
      openPeriodModal: handlers.periodos.openPeriodModal,
      askDeletePeriod: handlers.periodos.askDeletePeriod,
      colegiosLoading: schoolState.colegiosLoading,
      colegiosOptions: schoolState.colegiosOptions,
      resolveColegioNombreForView: derived.resolveColegioNombreForView
    },
    cursos: {
      adminCursosModalVisible: courseState.adminCursosModalVisible,
      rectorCursosModalVisible: courseState.rectorCursosModalVisible,
      closeCursosModal: handlers.cursos.closeCursosModal,
      loadingCursos: courseState.loadingCursos,
      openAdminCursoForm: handlers.cursos.openAdminCursoForm,
      cursoCrudColegioId: courseState.cursoCrudColegioId,
      cursoCrudPickerOpen: courseState.cursoCrudPickerOpen,
      setCursoCrudPickerOpen: courseState.setCursoCrudPickerOpen,
      colegiosLoading: schoolState.colegiosLoading,
      colegiosOptions: schoolState.colegiosOptions,
      resolveColegioNombreForView: derived.resolveColegioNombreForView,
      changeCursoCrudColegio: handlers.cursos.changeCursoCrudColegio,
      savingSede: courseState.savingSede,
      openSedeForm: handlers.cursos.openSedeForm,
      sedeFormVisible: courseState.sedeFormVisible,
      sedeForm: courseState.sedeForm,
      sedesLoading: derived.sedesLoading,
      sedesDisponibles: derived.sedesDisponibles,
      askDeleteSede: handlers.cursos.askDeleteSede,
      sortCursosForDisplay: derived.sortCursosForDisplay,
      cursosAsignados: derived.cursosAsignados,
      getNivelLabel: derived.getNivelLabel,
      resolveSedeNombreForView: derived.resolveSedeNombreForView,
      askDeleteCurso: handlers.cursos.askDeleteCurso,
      adminCursoFormVisible: courseState.adminCursoFormVisible,
      adminCursoFormProps: {
        styles: app.styles,
        adminCursoEditing: courseState.adminCursoEditing,
        adminCursoNombre: courseState.adminCursoNombre,
        setAdminCursoNombre: courseState.setAdminCursoNombre,
        adminCursoNivel: courseState.adminCursoNivel,
        setAdminCursoNivel: courseState.setAdminCursoNivel,
        adminCursoNivelPickerOpen: courseState.adminCursoNivelPickerOpen,
        setAdminCursoNivelPickerOpen: courseState.setAdminCursoNivelPickerOpen,
        adminCursoSedeId: courseState.adminCursoSedeId,
        setAdminCursoSedeId: courseState.setAdminCursoSedeId,
        adminCursoSedePickerOpen: courseState.adminCursoSedePickerOpen,
        setAdminCursoSedePickerOpen: courseState.setAdminCursoSedePickerOpen,
        sedesDisponibles: derived.sedesDisponibles,
        sedesLoading: derived.sedesLoading,
        savingCurso: courseState.savingCurso,
        nivelOptions: docenteState.NIVEL_OPTIONS || derived.NIVEL_OPTIONS,
        getNivelLabel: derived.getNivelLabel,
        resolveSedeNombre: derived.resolveSedeNombreForView,
        closeAdminCursoForm: handlers.cursos.closeAdminCursoForm,
        handleSaveAdminCurso: handlers.cursos.handleSaveAdminCurso
      },
      openRectorCursoForm: handlers.cursos.openRectorCursoForm,
      rectorCursoFormVisible: courseState.rectorCursoFormVisible,
      rectorCursoFormProps: {
        styles: app.styles,
        rectorCursoEditing: courseState.rectorCursoEditing,
        rectorCursoNombre: courseState.rectorCursoNombre,
        setRectorCursoNombre: courseState.setRectorCursoNombre,
        rectorCursoNivel: courseState.rectorCursoNivel,
        setRectorCursoNivel: courseState.setRectorCursoNivel,
        rectorCursoNivelPickerOpen: courseState.rectorCursoNivelPickerOpen,
        setRectorCursoNivelPickerOpen: courseState.setRectorCursoNivelPickerOpen,
        rectorCursoSedeId: courseState.rectorCursoSedeId,
        setRectorCursoSedeId: courseState.setRectorCursoSedeId,
        rectorCursoSedePickerOpen: courseState.rectorCursoSedePickerOpen,
        setRectorCursoSedePickerOpen: courseState.setRectorCursoSedePickerOpen,
        sedesDisponibles: derived.sedesDisponibles,
        sedesLoading: derived.sedesLoading,
        savingCurso: courseState.savingCurso,
        nivelOptions: derived.NIVEL_OPTIONS,
        getNivelLabel: derived.getNivelLabel,
        resolveSedeNombre: derived.resolveSedeNombreForView,
        closeRectorCursoForm: handlers.cursos.closeRectorCursoForm,
        handleSaveRectorCurso: handlers.cursos.handleSaveRectorCurso
      },
      sedeFormProps: {
        styles: app.styles,
        sedeEditing: courseState.sedeEditing,
        sedeNombre: courseState.sedeNombre,
        setSedeNombre: courseState.setSedeNombre,
        savingSede: courseState.savingSede,
        sedeError: courseState.sedeError,
        closeSedeForm: handlers.cursos.closeSedeForm,
        handleSaveSede: handlers.cursos.handleSaveSede
      }
    }
  };
}
