import React from 'react';
import ColegiosModals from './ColegiosModals';
import CursosModals from './CursosModals';
import DocentePanelModal from './DocentePanelModal';
import DocentesModals from './DocentesModals';
import EstudiantesCreateModal from './EstudiantesCreateModal';
import EstudiantesListModal from './EstudiantesListModal';
import HomeModalsContainer from './HomeModalsContainer';
import PeriodosModal from './PeriodosModal';
import ReportesModal from './ReportesModal';

export default function HomeScreenModals({
  styles,
  user,
  isAdmin,
  isMobileApp,
  docentePanelProps,
  estudiantesCreateProps,
  estudiantesListProps,
  periodosProps,
  cursosProps,
  colegiosProps,
  docentesProps,
  reportesProps,
  globalModalsProps
}) {
  return (
    <>
      <DocentePanelModal
        visible={docentePanelProps.docentePanelModalVisible}
        onClose={() => docentePanelProps.setDocentePanelModalVisible(false)}
        styles={styles}
        docentePerfilLoading={docentePanelProps.docentePerfilLoading}
        docentePerfilError={docentePanelProps.docentePerfilError}
        docentePerfilCursos={docentePanelProps.docentePerfilCursos}
        docenteMateriasAsignadasTotal={docentePanelProps.docenteMateriasAsignadasTotal}
        setDocentePanelModalVisible={docentePanelProps.setDocentePanelModalVisible}
        openCreateEstudianteModal={docentePanelProps.openCreateEstudianteModal}
      />

      <EstudiantesCreateModal
        visible={estudiantesCreateProps.estudianteCreateModalVisible}
        onClose={estudiantesCreateProps.closeCreateEstudianteModal}
        styles={styles}
        loadingCursos={estudiantesCreateProps.loadingCursos}
        savingEstudiante={estudiantesCreateProps.savingEstudiante}
        estudianteCreateCursoPickerOpen={estudiantesCreateProps.estudianteCreateCursoPickerOpen}
        setEstudianteCreateCursoPickerOpen={estudiantesCreateProps.setEstudianteCreateCursoPickerOpen}
        estudianteCreateCursoNombre={estudiantesCreateProps.estudianteCreateCursoNombre}
        cursosAsignados={estudiantesCreateProps.cursosAsignados}
        estudianteCreateCursoId={estudiantesCreateProps.estudianteCreateCursoId}
        changeEstudianteCreateCurso={estudiantesCreateProps.changeEstudianteCreateCurso}
        estudianteCreateMateriasDisponibles={estudiantesCreateProps.estudianteCreateMateriasDisponibles}
        estudianteCreateMaterias={estudiantesCreateProps.estudianteCreateMaterias}
        normalizeMateriaOption={estudiantesCreateProps.normalizeMateriaOption}
        toggleEstudianteCreateMateria={estudiantesCreateProps.toggleEstudianteCreateMateria}
        estudianteCreateForm={estudiantesCreateProps.estudianteCreateForm}
        setEstudianteCreateForm={estudiantesCreateProps.setEstudianteCreateForm}
        handleImportCsv={estudiantesCreateProps.handleImportCsv}
        selectedCsvFile={estudiantesCreateProps.selectedCsvFile}
        downloadExcelTemplate={estudiantesCreateProps.downloadExcelTemplate}
        downloadingTemplate={estudiantesCreateProps.downloadingTemplate}
        estudianteCreateError={estudiantesCreateProps.estudianteCreateError}
        uploadedStudents={estudiantesCreateProps.uploadedStudents}
        handleCreateEstudiante={estudiantesCreateProps.handleCreateEstudiante}
      />

      <EstudiantesListModal
        visible={estudiantesListProps.estudiantesModalVisible}
        onClose={estudiantesListProps.closeEstudiantesModal}
        styles={styles}
        resolveColegioNombre={estudiantesListProps.resolveColegioNombreForView}
        estudiantesColegioId={estudiantesListProps.estudiantesColegioId}
        setEstudiantesColegioPickerOpen={estudiantesListProps.setEstudiantesColegioPickerOpen}
        estudiantesColegioPickerOpen={estudiantesListProps.estudiantesColegioPickerOpen}
        colegiosLoading={estudiantesListProps.colegiosLoading}
        colegiosOptions={estudiantesListProps.colegiosOptions}
        changeEstudiantesColegio={estudiantesListProps.changeEstudiantesColegio}
        cursoSeleccionadoNombre={estudiantesListProps.cursoSeleccionadoNombre}
        setCursoPickerOpen={estudiantesListProps.setCursoPickerOpen}
        cursoPickerOpen={estudiantesListProps.cursoPickerOpen}
        loadingCursos={estudiantesListProps.loadingCursos}
        cursosAsignados={estudiantesListProps.cursosAsignados}
        cursoSeleccionado={estudiantesListProps.cursoSeleccionado}
        selectCursoEstudiantes={estudiantesListProps.selectCursoEstudiantes}
        estudiantesMateriasDisponibles={estudiantesListProps.estudiantesMateriasDisponibles}
        setEstudianteMateriaPickerOpen={estudiantesListProps.setEstudianteMateriaPickerOpen}
        estudianteMateriaPickerOpen={estudiantesListProps.estudianteMateriaPickerOpen}
        estudianteMateriaFiltro={estudiantesListProps.estudianteMateriaFiltro}
        ALL_MATERIAS_OPTION={estudiantesListProps.ALL_MATERIAS_OPTION}
        setEstudianteMateriaFiltro={estudiantesListProps.setEstudianteMateriaFiltro}
        normalizeMateriaOption={estudiantesListProps.normalizeMateriaOption}
        downloadingQrZip={estudiantesListProps.downloadingQrZip}
        downloadEstudiantesQrZip={estudiantesListProps.downloadEstudiantesQrZip}
        estudiantesLoading={estudiantesListProps.estudiantesLoading}
        estudiantesError={estudiantesListProps.estudiantesError}
        estudiantesFiltrados={estudiantesListProps.estudiantesFiltrados}
        qrZipProgress={estudiantesListProps.qrZipProgress}
        estudianteEditing={estudiantesListProps.estudianteEditing}
        estudianteEditForm={estudiantesListProps.estudianteEditForm}
        setEstudianteEditForm={estudiantesListProps.setEstudianteEditForm}
        savingEstudianteEdit={estudiantesListProps.savingEstudianteEdit}
        toggleEstudianteEditMateria={estudiantesListProps.toggleEstudianteEditMateria}
        handleUpdateEstudiante={estudiantesListProps.handleUpdateEstudiante}
        cancelEditEstudiante={estudiantesListProps.cancelEditEstudiante}
        startEditEstudiante={estudiantesListProps.startEditEstudiante}
        askDeleteEstudiante={estudiantesListProps.askDeleteEstudiante}
      />

      <PeriodosModal
        visible={periodosProps.periodModalVisible}
        onClose={periodosProps.closePeriodModal}
        styles={styles}
        periodModalScrollRef={periodosProps.periodModalScrollRef}
        editingPeriodo={periodosProps.editingPeriodo}
        isRectorCoordinador={periodosProps.isRectorCoordinador}
        canAdminFilterPeriodSchools={periodosProps.canAdminFilterPeriodSchools}
        periodSchoolId={periodosProps.periodSchoolId}
        periodSchoolPickerOpen={periodosProps.periodSchoolPickerOpen}
        setPeriodSchoolPickerOpen={periodosProps.setPeriodSchoolPickerOpen}
        setPeriodSchoolId={periodosProps.setPeriodSchoolId}
        setEditingPeriodo={periodosProps.setEditingPeriodo}
        colegiosLoading={periodosProps.colegiosLoading}
        colegiosOptions={periodosProps.colegiosOptions}
        resolveColegioNombre={periodosProps.resolveColegioNombreForView}
        periodForm={periodosProps.periodForm}
        setPeriodForm={periodosProps.setPeriodForm}
        periodos={periodosProps.periodos}
        periodFeedback={periodosProps.periodFeedback}
        setPeriodFeedback={periodosProps.setPeriodFeedback}
        days={periodosProps.days}
        months={periodosProps.months}
        years={periodosProps.years}
        hours={periodosProps.hours}
        minutes={periodosProps.minutes}
        monthNames={periodosProps.monthNames}
        adjustValue={periodosProps.adjustValue}
        cycleValue={periodosProps.cycleValue}
        savingPeriodo={periodosProps.savingPeriodo}
        handleSavePeriod={periodosProps.handleSavePeriod}
        formatPeriodSummary={periodosProps.formatPeriodSummary}
        formatPeriodDate={periodosProps.formatPeriodDate}
        formatPeriodTime={periodosProps.formatPeriodTime}
        getPeriodDurationLabel={periodosProps.getPeriodDurationLabel}
        openPeriodModal={periodosProps.openPeriodModal}
        askDeletePeriod={periodosProps.askDeletePeriod}
      />

      <CursosModals
        styles={styles}
        adminCursosModalVisible={cursosProps.adminCursosModalVisible}
        rectorCursosModalVisible={cursosProps.rectorCursosModalVisible}
        rectorSedesModalVisible={cursosProps.rectorSedesModalVisible}
        closeCursosModal={cursosProps.closeCursosModal}
        closeRectorSedesModal={cursosProps.closeRectorSedesModal}
        loadingCursos={cursosProps.loadingCursos}
        openAdminCursoForm={cursosProps.openAdminCursoForm}
        cursoCrudColegioId={cursosProps.cursoCrudColegioId}
        user={user}
        resolveColegioNombre={cursosProps.resolveColegioNombreForView}
        cursoCrudPickerOpen={cursosProps.cursoCrudPickerOpen}
        setCursoCrudPickerOpen={cursosProps.setCursoCrudPickerOpen}
        colegiosLoading={cursosProps.colegiosLoading}
        colegiosOptions={cursosProps.colegiosOptions}
        changeCursoCrudColegio={cursosProps.changeCursoCrudColegio}
        savingSede={cursosProps.savingSede}
        openSedeForm={cursosProps.openSedeForm}
        sedeFormVisible={cursosProps.sedeFormVisible}
        sedeForm={cursosProps.sedeForm}
        sedesLoading={cursosProps.sedesLoading}
        sedesDisponibles={cursosProps.sedesDisponibles}
        askDeleteSede={cursosProps.askDeleteSede}
        sortCursosForDisplay={cursosProps.sortCursosForDisplay}
        cursosAsignados={cursosProps.cursosAsignados}
        getNivelLabel={cursosProps.getNivelLabel}
        resolveSedeNombre={cursosProps.resolveSedeNombreForView}
        askDeleteCurso={cursosProps.askDeleteCurso}
        adminCursoFormVisible={cursosProps.adminCursoFormVisible}
        adminCursoFormProps={cursosProps.adminCursoFormProps}
        openRectorCursoForm={cursosProps.openRectorCursoForm}
        rectorCursoFormVisible={cursosProps.rectorCursoFormVisible}
        rectorCursoFormProps={cursosProps.rectorCursoFormProps}
        sedeFormProps={cursosProps.sedeFormProps}
      />

      <ColegiosModals
        styles={styles}
        {...colegiosProps}
      />

      <DocentesModals
        styles={styles}
        isAdmin={isAdmin}
        isMobileApp={isMobileApp}
        user={user}
        NIVEL_OPTIONS={docentesProps.NIVEL_OPTIONS}
        docenteNivelModalVisible={docentesProps.docenteNivelModalVisible}
        closeDocenteNivelConfigModal={docentesProps.closeDocenteNivelConfigModal}
        docenteNivel={docentesProps.docenteNivel}
        getNivelLabel={docentesProps.getNivelLabel}
        docenteSedeId={docentesProps.docenteSedeId}
        resolveSedeNombre={docentesProps.resolveSedeNombreForView}
        setDocenteNivelPickerOpen={docentesProps.setDocenteNivelPickerOpen}
        setDocenteSedePickerOpen={docentesProps.setDocenteSedePickerOpen}
        savingDocente={docentesProps.savingDocente}
        docenteNivelPickerOpen={docentesProps.docenteNivelPickerOpen}
        setDocenteNivel={docentesProps.setDocenteNivel}
        docenteSedePickerOpen={docentesProps.docenteSedePickerOpen}
        setDocenteSedeId={docentesProps.setDocenteSedeId}
        sedesLoading={docentesProps.sedesLoading}
        sedesDisponibles={docentesProps.sedesDisponibles}
        docenteCursosModalVisible={docentesProps.docenteCursosModalVisible}
        closeDocenteCursosConfigModal={docentesProps.closeDocenteCursosConfigModal}
        docenteCursos={docentesProps.docenteCursos}
        docenteCursosReturnTarget={docentesProps.docenteCursosReturnTarget}
        loadingCursos={docentesProps.loadingCursos}
        docenteCursosDisponibles={docentesProps.docenteCursosDisponibles}
        toggleDocenteCurso={docentesProps.toggleDocenteCurso}
        getNivelShortLabel={docentesProps.getNivelShortLabel}
        docenteMateriasDraft={docentesProps.docenteMateriasDraft}
        updateDocenteMateriaDraft={docentesProps.updateDocenteMateriaDraft}
        commitDocenteMateriaDraft={docentesProps.commitDocenteMateriaDraft}
        docenteCrudModalVisible={docentesProps.docenteCrudModalVisible}
        closeDocenteCrudModal={docentesProps.closeDocenteCrudModal}
        canAdminFilterDocenteSchools={docentesProps.canAdminFilterDocenteSchools}
        docenteColegioPickerOpen={docentesProps.docenteColegioPickerOpen}
        setDocenteColegioPickerOpen={docentesProps.setDocenteColegioPickerOpen}
        colegiosLoading={docentesProps.colegiosLoading}
        resolveColegioNombre={docentesProps.resolveColegioNombreForView}
        docenteColegioId={docentesProps.docenteColegioId}
        colegiosOptions={docentesProps.colegiosOptions}
        handleSelectDocenteCrudColegio={docentesProps.handleSelectDocenteCrudColegio}
        docentesLoading={docentesProps.docentesLoading}
        docentes={docentesProps.docentes}
        adminDocentesSearchTerm={docentesProps.adminDocentesSearchTerm}
        setAdminDocentesSearchTerm={docentesProps.setAdminDocentesSearchTerm}
        adminDocentesFiltrados={docentesProps.adminDocentesFiltrados}
        sortCursosForDisplay={docentesProps.sortCursosForDisplay}
        handleResetDocentePassword={docentesProps.handleResetDocentePassword}
        openAdminDocenteEditModal={docentesProps.openAdminDocenteEditModal}
        askDeleteDocente={docentesProps.askDeleteDocente}
        docenteEditing={docentesProps.docenteEditing}
        docenteForm={docentesProps.docenteForm}
        setDocenteForm={docentesProps.setDocenteForm}
        sanitizeDocenteNombreInput={docentesProps.sanitizeDocenteNombreInput}
        normalizeDocenteEmailInput={docentesProps.normalizeDocenteEmailInput}
        showDocentePassword={docentesProps.showDocentePassword}
        setShowDocentePassword={docentesProps.setShowDocentePassword}
        docenteError={docentesProps.docenteError}
        resetDocenteFormState={docentesProps.resetDocenteFormState}
        openDocenteNivelConfigModal={docentesProps.openDocenteNivelConfigModal}
        openDocenteCursosConfigModal={docentesProps.openDocenteCursosConfigModal}
        handleSaveDocente={docentesProps.handleSaveDocente}
        adminDocenteEditModalVisible={docentesProps.adminDocenteEditModalVisible}
        closeAdminDocenteEditModal={docentesProps.closeAdminDocenteEditModal}
        parseMateriasTexto={docentesProps.parseMateriasTexto}
        docenteCrudListModalVisible={docentesProps.docenteCrudListModalVisible}
        closeDocenteCrudListModal={docentesProps.closeDocenteCrudListModal}
        docentesSearchTerm={docentesProps.docentesSearchTerm}
        setDocentesSearchTerm={docentesProps.setDocentesSearchTerm}
        docentesSearchOpen={docentesProps.docentesSearchOpen}
        setDocentesSearchOpen={docentesProps.setDocentesSearchOpen}
        docentesSearchNormalized={docentesProps.docentesSearchNormalized}
        docentesSearchSuggestions={docentesProps.docentesSearchSuggestions}
        docentesFiltrados={docentesProps.docentesFiltrados}
        docentesModalVisible={docentesProps.docentesModalVisible}
        closeDocentesModal={docentesProps.closeDocentesModal}
        colegioSeleccionadoNombre={docentesProps.colegioSeleccionadoNombre}
        colegioPickerOpen={docentesProps.colegioPickerOpen}
        setColegioPickerOpen={docentesProps.setColegioPickerOpen}
        colegioSeleccionado={docentesProps.colegioSeleccionado}
        setColegioSeleccionado={docentesProps.setColegioSeleccionado}
        loadDocentesColegio={docentesProps.loadDocentesColegio}
        docentesError={docentesProps.docentesError}
      />

      <ReportesModal
        visible={reportesProps.reportesModalVisible}
        onClose={reportesProps.closeReportesModal}
        styles={styles}
        pad2={reportesProps.pad2}
        reportesDia={reportesProps.reportesDia}
        reportesMes={reportesProps.reportesMes}
        currentYear={reportesProps.currentYear}
        reportesColegioNombre={reportesProps.reportesColegioNombre}
        reportesCursoNombre={reportesProps.reportesCursoNombre}
        canAdminFilterReportSchools={reportesProps.canAdminFilterReportSchools}
        setReportesColegioPickerOpen={reportesProps.setReportesColegioPickerOpen}
        setReportesCursoPickerOpen={reportesProps.setReportesCursoPickerOpen}
        setReportesMesPickerOpen={reportesProps.setReportesMesPickerOpen}
        setReportesDiaPickerOpen={reportesProps.setReportesDiaPickerOpen}
        reportesBootLoading={reportesProps.reportesBootLoading}
        reportesLoading={reportesProps.reportesLoading}
        reportesColegioPickerOpen={reportesProps.reportesColegioPickerOpen}
        colegiosLoading={reportesProps.colegiosLoading}
        colegiosOptions={reportesProps.colegiosOptions}
        reportesColegioId={reportesProps.reportesColegioId}
        setReportesColegioId={reportesProps.setReportesColegioId}
        setReportesError={reportesProps.setReportesError}
        setReportesDetalle={reportesProps.setReportesDetalle}
        reportesCursoPickerOpen={reportesProps.reportesCursoPickerOpen}
        reportesCursos={reportesProps.reportesCursos}
        reportesCursoId={reportesProps.reportesCursoId}
        setReportesCursoId={reportesProps.setReportesCursoId}
        monthNames={reportesProps.monthNames}
        reportMonthOptions={reportesProps.reportMonthOptions}
        setReportesMes={reportesProps.setReportesMes}
        reportesMesPickerOpen={reportesProps.reportesMesPickerOpen}
        reportDayOptions={reportesProps.reportDayOptions}
        setReportesDia={reportesProps.setReportesDia}
        reportesDiaPickerOpen={reportesProps.reportesDiaPickerOpen}
        handleGenerateInasistenciaReport={reportesProps.handleGenerateInasistenciaReport}
        resetReportesFilters={reportesProps.resetReportesFilters}
        reportesError={reportesProps.reportesError}
        reportesDetalle={reportesProps.reportesDetalle}
      />

      <HomeModalsContainer
        styles={styles}
        {...globalModalsProps}
      />
    </>
  );
}
